spring:
  profiles:
    active: local

  datasource:
    url: jdbc:mysql://localhost:3306/jdbc
    username: root
    password: 991911
    driver-class-name: com.mysql.cj.jdbc.Driver

#jdbcTemplate
logging:
  level:
    org.springframework.jdbc: debug


##MyBatis
#mybatis:
#  type-aliases-package: hello.itemservice.domain
#  configuration:
#    map-underscore-to-camel-case: true
#logging:
#  level:
#    hello.itemservice.repository.mybatis: trace

## JPA
#logging:
#  level:
#    org.hibernate.sql: debug
#    org.hibernate.type.descriptor.sql.B